export default {
  FETCH_UPCOMING: "FETCH_UPCOMING",
  FETCH_HAPPY: "FETCH_HAPPY",
  FETCH_KEYWORD: "FETCH_KEYWORD",
  
  FETCH_SEARCH: "FETCH_SEARCH",
  FETCH_THEMOVIE: "FETCH_THEMOVIE",
  FETCH_CASTLIST: "FETCH_CASTLIST",

  CLEAR_THE_MOVIE: "CLEAR_THE_MOVIE",
  CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",

  FETCH_GIPHY_ERROR: "FETCH_GIPHY_ERROR"
};
