export default {
  FETCH_EXCITED: "FETCH_EXCITED",
  FETCH_HAPPY: "FETCH_HAPPY",
  FETCH_KEYWORD: "FETCH_KEYWORD",
  
  FETCH_SEARCH: "FETCH_SEARCH",
  CLEAR_SEARCH_RESULT: "CLEAR_SEARCH_RESULT",

  FETCH_GIPHY_ERROR: "FETCH_GIPHY_ERROR"
};
